import Head from 'next/head'
import { type } from 'os';
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  let [rafdata, setRafdata] = useState([]);
  let [page, setPage] = useState(0);
  let [rafselect, setRafselect] = useState("")
  let [fecha, setFecha] = useState(0) //fecha: Number =  9000 //121312000;  5160418900;
  let hoy = new Date();
  let strhoy = hoy.getFullYear() + "-0"+ hoy.getMonth() + "-"+ hoy.getDate();

  function llamada() {
    
    fetch("http://localhost:3000/api/fecha/"+fecha+"&page="+page+"&tags="+rafselect)
      .then((dat) => dat.json())
      .then((raf) => {
        
        return setRafdata(raf.salida);
      });
  }

  function pagdw(){
    if(page>0){
      setPage(--page);
       llamada();
    }
    
  }

  function pagup(){
    setPage(++page)
    llamada()
  }

  function select(e:any){
    e.preventDefault()
    setRafselect(e.target.value)
    setPage(0)
    llamada()
  }

  function minutos(e:any){
    setPage(0)
    setFecha(e.target.value*60)
  }
  function horas(e:any){
    setPage(0)
    setFecha(e.target.value*3600)
  }
  function dias(e:any){
    setPage(0)
    setFecha(e.target.value*86400)
  }
  function calendario(e:any){
    setPage(0)
     
    let aux:String=e.target.value[0]+e.target.value[1]+e.target.value[2]+e.target.value[3]
    let año:number = Number(aux)
    aux = e.target.value[5]+e.target.value[6];
    let mes:number =  Number(aux)  //mes es +1
    aux = e.target.value[8]+e.target.value[9];
    let dia:number =  Number(aux)
    let ahora:number = hoy.getFullYear()*31104000+(hoy.getMonth()+1)*2592000+hoy.getDate()*86400
    let datdi:number = dia*86400+mes*2592000+año*31104000
    let resta:number =ahora-datdi
     
    if (resta < 0) {
      alert("Selecione otra fecha");
    } else {
      setFecha(resta);
    }      
  }

  type noti = {
    objectID:string,
    title:string,
    author:string,
    created_at:string

  }

  useEffect(()=>{
    llamada()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>API-HN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={styles.p}> 
      <h4 className={styles.h4}>    
        Esta API REST se basa en la API de Algolia Search . Permite acceder a
        los datos de HN mediante mediante una tiempo X ó fecha. cómo solicitar
        datos?... la respuesta muestra Titulo,(sí lo tiene), Autor, Creado
        en(fecha de creado).</h4>   
      </p>

      <main className={styles.main}>
        <div className={styles.usuario}>
          <h1 className={styles.title}>Busca noticias de piratas informáticos </h1>         

          <div className={styles.tiempo}>
            <div>Desde cuanto tiempo inicia su busqueda?? </div>
            <input
              type="text"
              placeholder="Dias"
              id="dias"
              className={styles.inx}
              onChange={dias}
            />
            Dias;
            <br />
            <input
              type="text"
              placeholder="Horas"
              id="horas"
              className={styles.inx}
              onChange={horas}
            />
            Horas;
            <br />
            <input
            value={undefined}
              type="text"
              placeholder="Minutos"
              id="minutos"
              className={styles.inx}
              onChange={minutos}
            />
            Minutos;
            <br />
            <button onClick={llamada}  className={styles.boton} >Active su Busqueda por Tiempo</button>
          </div>
          <div className={styles.tiempo}>
            <div>Puede Buscar por fecha</div>
            <input type="date" id="fecha" min="2000-12-31" max={strhoy}  onChange={ calendario}  ></input>
            <br />
            <button onClick={llamada} className={styles.boton}>
              Active su Busqueda por Fehca
            </button>
          </div>
        </div>

        <div className={styles.lista}>
          Seleccione: Comentarios, Historias ó Encuesta
          <select name="tag1" className={styles.inx2 } value={rafselect} onChange={select}  >
            <option value="comment">Comentarios</option>
            <option value=" " selected>Seleccione</option>
            <option value="story">Historias</option>
            <option value="poll">Encuesta</option>
          </select>
          <button  className={styles.boton} onClick={pagdw} >&#60;</button>
          Pagina  {page}
          <button  className={styles.boton} onClick={pagup} >&#62;</button> 

          {rafdata.map((c:noti) => {
            return (
              <div key={c.objectID}>
                <h4 className={styles.h4}>
                  Titulo= {c.title}, Autor: {c.author}, Creado en:{" "}
                  {c.created_at}
                </h4>
              </div>
            );
          })}
          <button  className={styles.boton} onClick={pagdw} >&#60;</button>
          Pagina  {page}
          <button  className={styles.boton} onClick={pagup} >&#62;</button> 
        </div>
      </main>

      <footer className={styles.footer}>
        <h3>Contacteme</h3>
        <div>          
          Github:
          <a href="https://github.com/SarriaRafael" target="_blank">
            https://github.com/SarriaRafael
          </a>
        </div>
        <div>
          linkedin:
          <a
            href="https://www.linkedin.com/in/rafael-sarria-salcedo-74a121219/"
            target="_blank"
          >
            https://www.linkedin.com/in/rafael-sarria-salcedo-74a121219/
          </a>
        </div>
        <div> gmail: rafael3sarria@gmail.com </div>
        <h3>Espero conocerte muy pronto </h3>        
      </footer>
    </div>
  );
}
